### ISSUE TITLE
How to use MobileAPI in another application

### ISSUE THREAD

**Issue by koyaja** [qmatic/mobile-ticket#2]
Hi svpt I would like to use the library mobileticket.js in an ionc application how to configure Thank you in advance

**Comment by pergrapatin** [comment]
Hi Koyaja,

The readme file should explain how to use mobileticket.js there is not that much of configuration. It should be possible to use in Ionic.

It expects an Qmatic API Gateway on the other side. If you need implementation help contact Qmatic Professional support.

Regards

**Comment by koyaja** [comment]
Please to heberger offline mobileticket.js or should you put the configuration file (for integrated in another project for example)

**Comment by thushan83** [comment]
If you want to use the mobileticket.js API in another application or a framework. First you need to clone the source and copy the mobileticket.js file that resides in "mobile-ticket/src/libs/js/" to your ionic project. Then you can refer the mobileticket,js from your ionic project and use the API.

**Comment by koyaja** [comment]
think
Ok I cloned the project and I included the mobileticket.js in my project but the problem is how to give the address GETWAY API to the MobileTiketAPI

**Comment by thushan83** [comment]
@koyaja 

Mobile-Ticket solution by default is developed to host on Node.js. So the Node.js server will communicate with the API GATEWAY. The server.js resides in "mobile-ticket\node" folder handles server functionality. This server.js file contains some proxy functionality to redirect request from mobileticket.js to API GATEWAY, it reads relavent configurations from proxy-config.json which is in the same folder (including API GATEWAT IP, PORT etc). You have two options easiest is to use the same Node.js deployment method we have provided and host your ionic app in there, so the mobileticket.js should work with API GATEWAY given the correct configurations. The second option is if you cannot afford to run your ionic application on Node.js and should run on a different platform, you need to rewrite the proxy functionality in server.js and functionality to read the configurations from  proxy-config.json. Hope this answers your question :)

**Comment by koyaja** [comment]
Ok thank you very much considering your time if you can help me it will also be a big thank you because the application will not be hosted on node so I have to rewrite the server.js so your help to rewrite will be welcome

**Comment by koyaja** [comment]
@thushan83 
I am from SOFT-IT we are partner of Qmatic in Benin

**Comment by thushan83** [comment]
@koyaja @pergrapatin 

If you need help to customize the proxy implementation you can contact Qmatic Professional support.

**Comment by koyaja** [comment]
I try to access api GATEWAY here is the error I get
`XMLHttpRequest can not load http://192.168.0.159:9090/MobileTicket/branches/?longitude=0&latitude=0&radius=2147483647. Response to preflight request does not pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.0.159:8100' is therefore not allowed access. The response had HTTP status code`
Help me please

**Comment by pergrapatin** [comment]
You need a backend on your webserver to route req to API GW otherwise you will run into issues like this. As the error code suggests you have a variant of cross site scripting issue.

**Comment by koyaja** [comment]
hello How to use appointment making in mobileticket

**Comment by jesrus** [comment]
Appointment creation is currently not included in Mobile Ticket.

**Comment by koyaja** [comment]
Ok please i can know how it works

**Comment by jesrus** [comment]
On Qmatic World under Products / Orchestra /Mobile Ticket you can find information and documentation for mobile ticket. 

I think the information here would give you the overview of the Mobile Ticket functionality.

**Comment by koyaja** [comment]
ok thank
